language: node_js
node_js:
  - 'node'
install:
  - npm install
script:
  - npm run test
before_deploy:
  - npm run build-storybook
  - npm run build-components
deploy:
  - provider: surge
    skip_cleanup: true
    project: ./storybook/
    domain: nasa-1975.surge.sh
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: simon.schwartz0@gmail.com
    api_key:
      secure: "iQFiME+aM0J6EWZA9biEqRjURs75Yj+Jmep3s1UEz8GK8NcXv6On19YXbcF/R8h4jqFQjmJBe1mGbYumge79vm/HMpaWd8onbxyG1c3zvxTRU3sT/O/yMGbokrLVS0SDBte4eER+WyKLIq0Kl7kApmfKnt1PZH+Fca17lo3C67NL2OmDElEVuw159Ce8D80IZWE1oViCQtFcNH2Hb1aSac0ivwlZsXPjtmC0j66TwV8xQSlGY2VO5FqA6z1Bpd9uKfxycNyvu9tEK5b/S1v65AHDfK2vgNjaGDzLU5gHF1bDo6YHq2XtOWuutpcVAxzPnIpIwfIz3/FvYESMB9LqUQxKiXY8f9YEQTdbtEV2waTc4GOULu+RAjXjYtAug1lXO+FaU4SgPVEbnKxo+V1pXUb19AsDnfiY7k+rDBb3erOdAR0kU6RCoVsxkU0JvNfOfRkVad04+gBrFo+LSW4jV0Yv46h1jitqx3X1zsK152cQ9dpvGdcHTU0DDk7Kh1WV8hx6dAEuQ8XXL/o/dAC1aBbxkEjw/4uz4uvhxNHdI2oNY3ZJytDZhSNxZwsTXEwJItmKeVLcZ44w7UWTjPzvB08fFEIPZw4nIjkbelaIAK8FCjM+L2vE9/lMnX08gekfsXO7esCzPUiEVKzMlr7R2it6R5A15X3W4T2yBMioz98="
    on:
      tags: true
      branch: master
